# Generated by Django 4.2 on 2023-04-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('critics_consensus', models.TextField(blank=True, null=True)),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('amount_reviews', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approval_percentage', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
